"""esquema inicial

Revision ID: 372f17588949
Revises: 
Create Date: 2026-07-03 08:55:39.593124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372f17588949'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('juridico_defecto', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('expedientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_orden', sa.Integer(), nullable=True),
    sa.Column('dias', sa.Integer(), nullable=True),
    sa.Column('expediente', sa.String(length=50), nullable=False),
    sa.Column('interesado', sa.String(length=255), nullable=True),
    sa.Column('asunto', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('situacion_abierto', sa.Boolean(), nullable=False),
    sa.Column('fecha_expediente', sa.Date(), nullable=True),
    sa.Column('estado_origen', sa.String(length=255), nullable=True),
    sa.Column('fase', sa.String(length=50), nullable=False),
    sa.Column('documentacion_pendiente', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio_evento', sa.Date(), nullable=True),
    sa.Column('fecha_fin_evento', sa.Date(), nullable=True),
    sa.Column('tecnico_asignado_id', sa.Integer(), nullable=True),
    sa.Column('juridico_asignado_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['juridico_asignado_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tecnico_asignado_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expediente')
    )
    op.create_table('turnos_tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('semana_inicio', sa.Date(), nullable=False),
    sa.Column('semana_fin', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fase_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fase_anterior', sa.String(length=50), nullable=True),
    sa.Column('fase_nueva', sa.String(length=50), nullable=True),
    sa.Column('documentacion_anterior', sa.String(length=50), nullable=True),
    sa.Column('documentacion_nueva', sa.String(length=50), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fase_historico')
    op.drop_table('turnos_tecnico')
    op.drop_table('expedientes')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
